# Generated by Django 4.0.1 on 2022-01-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de atualização')),
                ('logradouro', models.CharField(max_length=128)),
                ('bairro', models.CharField(max_length=128)),
                ('numero', models.SmallIntegerField()),
                ('data_remocao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
